production:
#  adapter: mysql2  
#  reconnect: true
#  database: culturalstream_production
#  pool: 5
#  username: culturalstream
#  password: tuca
#  encoding: utf8
#  collation: utf8_general_ci
  adapter: postgresql
  database: culturalstream_production
  pool: 5
  host: localhost
  username: culturalstream
  password: tuca
  encoding: utf8
  collation: utf8_general_ci

